### ISSUE TITLE
gst-bayer2rgb-neon

### ISSUE THREAD

**Issue by thile732** [sigma-embedded/meta-de.sigma-chemnitz#1]
hi, i am using your gst-bayer2rgb-neon and bayer2rgb-neon libraries to convert rggb to rgb images. I'm facing the problem that the converted image is missing information in the last columns and rows, causing that area to turn black. For example:
when I use the command:
gst-launch-1.0 filesrc location=/tmp/cpt_0.raw blocksize=384000 ! "video/x-bayer,format=rggb,width=800,height=480,framerate=1/1" ! bayer2rgb ! jpegenc ! filesink location=output_bayer2rgb.jpg
![image](https://github.com/sigma-embedded/meta-de.sigma-chemnitz/assets/82926718/53a4b3bf-e8b0-465f-80ec-c2856d370492)

and when I use the command:
gst-launch-1.0 filesrc location=/tmp/cpt_0.raw blocksize=384000 ! "video/x-bayer,format=rggb,width=800,height=480,framerate=1/1" ! bayer2rgbneon ! jpegenc ! filesink location=output_bayer2
rgbneon.jpg
![image](https://github.com/sigma-embedded/meta-de.sigma-chemnitz/assets/82926718/0417601e-06de-4d8f-ab4d-7687fe79d6ab)

I have used both version 0.4 and 0.6.1 but the same problem still occurs. If you can, please take a moment to look. Thank you very much!

**Comment by ensc** [comment]
Conversion of border regions is not implemented atm; actually there are two special cases:

- averaging needs to read the surrounding pixels in every direction, that's why the first and last two columns/rows are ignored
- NEON optimization reads 8 pixels (per color) at once where 1 pixel is shared between two rounds; number of read columns is aligned to 2 * 7 = 14 hence.

You will have to postprocess the image and remove the border manually.

**Comment by thile732** [comment]
Sorry for the late response.
Based on your suggestion, after looking into the source code of this library, perhaps the problem lies in how to handle the edges of the image. I made a few adjustments and got the photo after processing with zero borders.
Thanks for your help!
